### ISSUE TITLE
Адаптация интерфейса

### ISSUE THREAD

**Issue by IStormtrooperI** [Kirlovon/Kinopoisk-Watch#10]
Привет, можете сделать адаптацию окна плеера под маленькие окна. С трудом получается развернуть плеер на весь экран.

![image](https://user-images.githubusercontent.com/77672564/196603529-29320709-5677-4920-837c-4cb1a76b7b38.jpeg)

**Comment by Kirlovon** [comment]
Обновил интерфейс, теперь должно смотреться лучше
<img width="311" alt="image" src="https://user-images.githubusercontent.com/18380935/196818056-148bebeb-fc04-4db7-ae6e-237b941769df.png">

**Comment by IStormtrooperI** [comment]
Теперь элементов управления видео в левом верхнем и нижнем правом вообще не видно.

![image](https://user-images.githubusercontent.com/77672564/196824152-d71dab65-acd7-48ac-8537-b9464de70427.png)

**Comment by Kirlovon** [comment]
Вывести элементы управления не получится, плеер это отдельный iframe. Что это за браузер, Safari на IOS? Какое разрешение экрана? UI должен выглядеть немного по другому, попробую возпроизвести этот баг.

**Comment by IStormtrooperI** [comment]
Да ios, 640x1136

**Comment by IStormtrooperI** [comment]
я имел ввиду уменьшить плеер настолько, чтобы можно было увидеть все элементы управления. плеер же в любом случае будут на весь экран разворачивать соответствующей кнопкой

**Comment by srgvsky** [comment]
После адаптации только у меня пропали субтитры или это общая фишка?...

**Comment by Kirlovon** [comment]
@srgvsky Можешь отправить ссылку на фильм, в котором пропали субтитры? Попробую исправить.

**Comment by srgvsky** [comment]
> 
Раньше тут точно были сабы
https://kinopoisk-watch.org/player/?id=464963

**Comment by Kirlovon** [comment]
Сори, @IStormtrooperI совсем забыл сказать, что я обновил верстку, теперь должно хорошо смотреться на телефонах.

**Comment by Kirlovon** [comment]
@srgvsky, субтитры в самом плеере работают, тут скорее всего проблема связана с хостингом конкретно этого сериала, возможно у них эти субтитры не загружены или неправильно настроены. Я никак не смогу повлиять на это.
