### ISSUE TITLE
на hd.kinopoisk.ru не пашет.

### ISSUE THREAD

**Issue by ffdown** [Kirlovon/Kinopoisk-Watch#11]
появились ссылки типа hd.kinopoisk.ru а там скрипт не пашет.

**Comment by Kirlovon** [comment]
@ffdown, Можно пример такой ссылки?

**Comment by DimaFlexYT** [comment]
https://kinopoisk-watch.org/player/?id=502302 не работает (не загружает фильм) 
Ссылка на сам кинопоиск - https://www.kinopoisk.ru/film/502302/

**Comment by DimaFlexYT** [comment]
Хотелось бы уточнить, плеер работает в данный момент стабильно? Выдало 3/3 нерабочих фильмов

**Comment by 33rddayofsummer** [comment]
В хроме не получается смотреть, пишет "Не удалось загрузить фильм!", хотя вчера работало всё. Ссылка ниже
https://kinopoisk-watch.org/player/?id=1108690

**Comment by Kirlovon** [comment]
@33rddayofsummer у меня эта ссылка работает. Если у вас тоже, то это были временные неполадки, не зависящие от меня.

**Comment by Kirlovon** [comment]
@DimaFlexYT Да, должен работать стабильно. Какие именно фильмы у вас не открываются?

**Comment by DimaFlexYT** [comment]
@Kirlovon В данный момент работает, вчера видимо были неполадки)

**Comment by DimaFlexYT** [comment]
> появились ссылки типа hd.kinopoisk.ru а там скрипт не пашет.

Нашёл решение, придётся дописать 
![image](https://user-images.githubusercontent.com/101525546/204470835-f1bc88c0-1331-4f12-963b-0b3d53bd6276.png)
Переходишь в редактор скрипта, настройки и в "Пользовательские @matches" добавляешь параметр *://hd.kinopoisk.ru/*

**Comment by Kirlovon** [comment]
@DimaFlexYT Плеер использует ID Кинопоиска для загрузки фильмов, и кажется у Kinopoisk HD используются другие ID, отличающиеся от тех, которые используются на основном сайте. Могу ошибаться, киньте пример ссылки с hd.kinopoisk.ru, я перепроверю.

**Comment by DimaFlexYT** [comment]
@Kirlovon Ну по идеи ссылки данного формата (скину несколько, на всякий)
https://hd.kinopoisk.ru/film/44891de9e4807e8e94081ce76c2a6315 
https://hd.kinopoisk.ru/?rt=c069f386d3e9461f9fa585ed2ec8dbea 
https://hd.kinopoisk.ru/?rt=4ee03cdcd84ab743b09b773052ac3a72 
https://hd.kinopoisk.ru/personal?rt=4db339aee69851de96542d394581a8a3
https://hd.kinopoisk.ru/?rt=47b5c9002d6c7312a0993f857e120b31
Не особо понял, по какому коду закодированы id, очень странно

**Comment by Kirlovon** [comment]
@DimaFlexYT id фильма получается из ссылки, а именно из последних цифр:

> kinopoisk.ru/film/**506133**

И так как в Kinopoisk HD используется другой формат id, фильмы загрузить не получится.
