### ISSUE TITLE
Уточнение по коду 

### ISSUE THREAD

**Issue by DimaFlexYT** [Kirlovon/Kinopoisk-Watch#12]
Приветствую, хотелось бы уточнить 
Есть код ли код с пояснениями какой код за что отвечает? 
Хотелось бы увидеть хоть какие-то пометки, которые помогут осмыслить строки, возможно какие-то мысли подкину для улучшения (Пока не особо сильно разбираюсь)

**Comment by Kirlovon** [comment]
Привет, если вы про комментарии в коде, то они уже там есть, я не думаю, что могу добавить туда что то ещё. Если есть какие то конкретные вопросы по определенным строчкам кода, то могу попробовать объяснить их здесь. 🙂
