### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by Fy0urM** [Kirlovon/Kinopoisk-Watch#16]
Ресурс недоступен для пользователей из россии со стороны хоста?

**Comment by VolodinAS** [comment]
Подтверждаю недоступность https://kinopoisk-watch.org/

**Comment by Kirlovon** [comment]
@Fy0urM, Нет, похоже, домен попал в какой-то список заблокированных ресурсов, так что блокировка со стороны провайдеров.

**Comment by Fy0urM** [comment]
@Kirlovon, Таки да, проверял в реестре сам адрес ресурса и он не находился, решил проверить ип который возвращает сайт и таки он заблокирован. Ограничение Федеральным законом от 27.07.2006 № 149-ФЗ
