### ISSUE TITLE
При соединении с kinopoisk-watch.org произошла ошибка. PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by gefestdev** [Kirlovon/Kinopoisk-Watch#19]

**Comment by IStormtrooperI** [comment]
![image](https://user-images.githubusercontent.com/77672564/209725695-c68bc1de-4c98-42a8-b9ad-2a312765527b.png)

**Comment by Fy0urM** [comment]
роскомпозор заблочил, проверить тут https://blocklist.rkn.gov.ru
