### ISSUE TITLE
Сайт заблокирован на территории РФ

### ISSUE THREAD

**Issue by Mafiozy42** [Kirlovon/Kinopoisk-Watch#20]
С недавнего времени при использовании расширения (непосредственно переходе на плеер) показывается страница, что сайт заблокирован. Работает только через ВПН

**Comment by Kirlovon** [comment]
Добавил альтернативную версию скрипта, использующую не заблокированную ссылку плеера. Установить можно тут: https://github.com/Kirlovon/Kinopoisk-Watch/blob/master/kinopoisk-watch-alternative.user.jsч
