### ISSUE TITLE
Сайт не работает (Решение тут)

### ISSUE THREAD

**Issue by madonchik123** [Kirlovon/Kinopoisk-Watch#21]
Сайт не работает в рф и приходится использовать впн 
я сделал свою копию сайта и вы можете установить её по вот этой ссылке https://github.com/madonchik123/Kinopoisk-watch/raw/main/kinopoisk-watch.user.js

**Comment by Kirlovon** [comment]
Спасибо за временное решение! Добавил альтернативную версию скрипта, использующую не заблокированную ссылку плеера.
