### ISSUE TITLE
Фильм не найден / Не работает плеер

### ISSUE THREAD

**Issue by WistFall** [Kirlovon/Kinopoisk-Watch#25]
Уже несколько дней не работает
Пишет - "Не удалось загрузить фильм"
Переустановка скрипта не помогла. Альтернативные скрипты тоже не помогают.

**Comment by Kirlovon** [comment]
Привет, поделитесь ссылкой на фильм, который у вас не открывается. Возможно, этот фильм недоступен ни на одном из ресурсов.

**Comment by demo2111** [comment]
![image](https://github.com/Kirlovon/Kinopoisk-Watch/assets/140321998/a757427a-cebb-4874-baec-4d30f60f8726)
 у меня тоже не работает
