### ISSUE TITLE
Ломается плеер при просмотре

### ISSUE THREAD

**Issue by therealadik** [Kirlovon/Kinopoisk-Watch#30]
Начинаю смотреть фильм, а через минуту-две просто темный экран и все. Спасает только обновление страницы и потом снова так. Почините пж

**Comment by therealadik** [comment]
Это происходит на конце фильма, за 1-2 минуты

**Comment by Kirlovon** [comment]
@therealadik Можешь поделится ссылкой на фильм и плеером (цифра с лева), с которым подобное происходит?

**Comment by therealadik** [comment]
все ушло, странно, но теперь все работает

**Comment by therealadik** [comment]
закрываю
