### ISSUE TITLE
Предложение по улучшению скрипта: поддержка плееров Bazon и Collaps

### ISSUE THREAD

**Issue by LoveCaxarok** [Kirlovon/Kinopoisk-Watch#31]
Добрый день!

Я являюсь пользователем вашего скрипта и хотел бы предложить некоторые улучшения. Мои самые любимые видеоплееры - Bazon и Collaps, и они доступны на сайте Kinobox.tv.

Было бы замечательно, если бы вы могли добавить поддержку этих плееров в вашем скрипте. Лично я считаю, что они предоставляют отличный опыт просмотра, и они мне нравятся.

Если возникнут трудности с добавлением этих плееров, мне было бы интересно узнать причину, почему такое изменение может быть затруднительным. Также интересно узнать, планируете ли вы добавить поддержку Bazon и Collaps в будущих обновлениях вашего скрипта.

Спасибо за вашу работу и внимание к нашим запросам!

С наилучшими пожеланиями,
LoveCaxarok

**Comment by Kirlovon** [comment]
Привет! Плееры Bazon и Collaps требуют индивидуальной настройки, и не работают по умолчанию. Планирую добавить их чуть позже.

**Comment by Kirlovon** [comment]
621140b603c147a6e4c68c4f37fd1c67608f8483 Добавил больше плееров! (Включая Bazon)

**Comment by LoveCaxarok** [comment]
Спасибо тебе за Collaps, но Bazon так и не работает. У меня есть расширение для просмотра на Кинопоиске, и там Bazon работает, но у тебя почему-то нет. Ты же подавлял не только Collaps, но и другие плееры, и они тоже не работают. Можно сказать, что ты только добавил Collaps, и все остальное осталось без изменений. Можешь ли ты как-то починить это или сделать так, чтобы Bazon заработал? Вот расширение если что:https://chrome.google.com/webstore/detail/kinopoisk-player-фильмысе/gbdfmlkiafpjocliomeeabjikgbjgian?hl=ru
(плеера которые не работают вместо них просто белый экран)

**Comment by barbaduk** [comment]
> [621140b](https://github.com/Kirlovon/Kinopoisk-Watch/commit/621140b603c147a6e4c68c4f37fd1c67608f8483) Добавил больше плееров! (Включая Bazon)

Bazon не работает, белый экран (даже через кучу разных впн) ☹

**Comment by Kirlovon** [comment]
https://github.com/Kirlovon/Kinopoisk-Watch/issues/32
