### ISSUE TITLE
Проблемы и предложения по улучшению функционала плееров 

### ISSUE THREAD

**Issue by LoveCaxarok** [Kirlovon/Kinopoisk-Watch#32]
Я конечно понимаю что просить о таком как бы не сильно правильно(я хочу сказать то что не только я пользуюсь твоим скриптом,а и другие пользователи и им может это изменение не понравится, но когда был yohoho,Collaps был всегда первым плеером и при запуске скрипта сразу-же включался Collaps плеер,я понимаю что не мне сильно очень уж трудно просто выбрать нужный мне плеер ,но тогда мне нравилось что Collaps был на первой месте,да-да я пользуюсь в всегда Collaps плеером т.к считаю его более лучшим всем остальным своим функционалом(первый в списке плееров при переходе на сайт для просмотра фильмов)).
Bazon так и не работает. У меня есть расширение для просмотра на Кинопоиске, и там Bazon работает, но у тебя почему-то нет,хотелось бы если есть возможность чтобы Bazon работал в скрипте. Ты же подавлял не только Collaps, но и другие плееры, и они тоже не работают. Все остальное осталось без изменений, кроме работающих HDVB Player и Colaps(новых добавленых плееров) . Можешь ли ты как-то починить это или сделать так, чтобы Bazon заработал? Вот расширение если что:https://chrome.google.com/webstore/detail/kinopoisk-player-фильмысе/gbdfmlkiafpjocliomeeabjikgbjgian?hl=ru
(плеера которые не работают вместо них просто белый экран)

**Comment by Kirlovon** [comment]
Привет, сделал Collaps первым в списке! С Bazon надо разбираться, так как у меня он работает. У тебя установлен оригинальный или альтернативный скрипт?

По поводу остальных плееров, какие из них в данный момент работают? В моем случае работают все кроме Ashidi.

**Comment by LoveCaxarok** [comment]
альтернативный скрипт

**Comment by ffdown** [comment]
Как это поставить на smartphone Android?

**Comment by Kirlovon** [comment]
@ffdown Установите браузер, поддерживающий Tempermonkey. Вроде бы мобильный Firefox должен подойти.

**Comment by Kirlovon** [comment]
@LoveCaxarok На данный момент Bazon работает только на основном домене. Альтернативная версия скрипта использует другой домен, для которого токен для работы Bazon требуется настроить отдельно. Для этого придется перенастроить хостинг, так как сейчас он автоматически использует код основного сайта.

Есть ли какая то причина, по который именно этот плеер так необходим?

**Comment by LoveCaxarok** [comment]
@Kirlovon Спасибо тебе за пояснение
Но я бы хотел знать будет ли он вообще в альтернативном скрипте в будущем когда нибудь работать
1)Да будет но позже
2)Возможно 50/50(может будет или нет)
3)Нет в альтернативном скрипте не будет bazon
()
причина в том что мне нравится bazon тем что качество всегда лучше чем в других плеерах когда я захожу на фильм и вижу что качесво во всех плеерах например hd(720) то в bazone иногда  fullhd(1080) иногда даже когда качесво во всех плеерах full hd то в bazone оно как то лучше выгледело.

**Comment by LoveCaxarok** [comment]
@Kirlovon Спасибо тебе за пояснение
Но я бы хотел знать будет ли он вообще в альтернативном скрипте в будущем когда нибудь работать
1)Да будет но позже
2)Возможно 50/50(может будет или нет)
3)Нет в альтернативном скрипте не будет bazon
(Я бы хотел что бы ты на мой вопрос ответил как бы так,чтобы я угомонился )
Причина в том что мне нравится bazon тем что качество всегда лучше чем в других плеерах когда я захожу на фильм и вижу что качесво во всех плеерах например hd(720) то в bazone иногда fullhd(1080) иногда даже когда качесво во всех плеерах full hd то в bazone оно как то лучше выгледело.

**Comment by Kirlovon** [comment]
@LoveCaxarok Окей. Я займусь этим в свободное время, так что все будет, но попозже!

**Comment by R4M5EY** [comment]
Перестало работать

![Screenshot_1](https://github.com/Kirlovon/Kinopoisk-Watch/assets/52279180/6f87094e-8745-413f-b5e0-513f65792614)

**Comment by Kirlovon** [comment]
Сайт Bazon перестал быть доступен, а поддержка этого плеера больше не указана в документации Kinobox.
