### ISSUE TITLE
Будет ли работать Bazon?

### ISSUE THREAD

**Issue by LoveCaxarok** [Kirlovon/Kinopoisk-Watch#33]
Здраствуйте, мне все ещё интереесно заработает ли bazon?(да он до сих пор не работает)

![image](https://github.com/Kirlovon/Kinopoisk-Watch/assets/104596120/dc157327-4b67-400d-9244-49884ca91a13)

https://github.com/Kirlovon/Kinopoisk-Watch/assets/104596120/93c954cf-5e29-4c31-b6e3-5bcb9958a685

**Comment by Kirlovon** [comment]
https://github.com/Kirlovon/Kinopoisk-Watch/issues/32
