### ISSUE TITLE
Названия в заголовке страницы

### ISSUE THREAD

**Issue by Zivers88** [Kirlovon/Kinopoisk-Watch#36]
Привет!
А можно как-то сделать, чтобы название фильма подтягивалось в заголовок страницы?

А то у меня открыто много вкладок с разными фильмами и каждая вместо уникального названия фильма и пр. имеет вот такой вид

![2024-03-09_173422](https://github.com/Kirlovon/Kinopoisk-Watch/assets/83170968/d96a3bb9-57b8-4e6f-ac94-0b31dc48f6f6)

**Comment by Kirlovon** [comment]
Спасибо за идею! Добавил отображение названий, обновите скрипт что бы все заработало.
