### ISSUE TITLE
Плеер перестал работать на яндекс браузере 

### ISSUE THREAD

**Issue by Ananimus671hydra** [Kirlovon/Kinopoisk-Watch#38]
Удалил Яндекс браузер и установил новую версию 
скрипт перестал работать не понимаю почему...
![photo_2024-07-08_06-03-47](https://github.com/Kirlovon/Kinopoisk-Watch/assets/174981097/467a505e-f2e4-4985-828d-9065d10ea797)

**Comment by Ananimus671hydra** [comment]
все таки установил другую версию под названием Tampermonkey Legacy (MV2)
все работает отлично
![image](https://github.com/Kirlovon/Kinopoisk-Watch/assets/174981097/120b0a38-9856-48fb-9eb5-c8f44475d5aa)
![image](https://github.com/Kirlovon/Kinopoisk-Watch/assets/174981097/66cde7cf-f610-42e4-8654-b8d9d2b15a0d)

**Comment by Kirlovon** [comment]
С выпуском Manifest v3, для полноценной работы Tempermonkey требуется в браузере включить режим разработчика. Больше можно прочитать [здесь](https://www.tampermonkey.net/faq.php?locale=ru#Q209). Или, как уже писал @Ananimus671hydra, можно установить Legacy версию Tempermonkey.
