### ISSUE TITLE
Collaps подгружает другой фильм

### ISSUE THREAD

**Issue by srgvsky** [Kirlovon/Kinopoisk-Watch#39]
Почему-то при переходе со страницы сериала Медсестра 2016 [https://www.kinopoisk.ru/series/999459/](url) в плеере Collaps грузится Спросите медсестру 2020 [https://www.kinopoisk.ru/series/1323569/](url) 
на остальных плеерах все нормально при этом 
а если переходить со страницы "Спросите медсестру" - там вообще нет варианта с Collaps почему-то

**Comment by Kirlovon** [comment]
Похоже это из за неправильного ID, указанного в базе данных Collaps. Не могу повлиять на это.

**Comment by LoveCaxarok** [comment]
@srgvsky можешь написать в тех поддержку Collaps
Вот их тг:https://t.me/collaps_support
