### ISSUE TITLE
Не показывает ни один фильм

### ISSUE THREAD

**Issue by yungd1plomat** [Kirlovon/Kinopoisk-Watch#5]
![изображение](https://user-images.githubusercontent.com/64736191/163581880-13f110bc-bb98-487f-8adc-d9c8ba971ea2.png)

**Comment by Kirlovon** [comment]
Плагин работает на основе плеера [Yohoho](https://yohoho.cc/), который сейчас работает не очень стабильно, и я не могу повлиять на это. Такое уже происходило ранее, скорее всего он заработает в течении нескольких дней.
