### ISSUE TITLE
не правильно подставляется id

### ISSUE THREAD

**Issue by Stsiraphim** [Kirlovon/Kinopoisk-Watch#8]
при переходи с кинопоиска на плеер не верно подставляется id сериала или фильма все время подставляется 
https://kirlovon.dev/Kinopoisk-Watch/?id=1313569 Какой то (сказачный патруль) детский мультфильм

**Comment by AnKh99** [comment]
в 28й строке скрипта нужно добавить в конце ссылки '/'
const PLAYER_LINK = 'https://kirlovon.github.io/Kinopoisk-Watch/';

**Comment by Kirlovon** [comment]
Видимо, Github Pages обновил поведение их веб сервера, и теперь query параметры передаются по-другому. Исправил, переустановите скрипт. @AnKh99 - спасибо за наводку!
