### ISSUE TITLE
возможно ли добавить поддержку kinorium?

### ISSUE THREAD

**Issue by DmitriyPekar** [Kirlovon/Kinopoisk-Watch#9]
https://kinorium.com/

**Comment by Kirlovon** [comment]
Плеер, который я использую для показа фильмов, находит фильмы по их ID с Кинопоиска. Этот плеер не подойдет для Kinorium, так как на этом сайте использются другие ID. В любом случае, пока что я не планирую заниматся потдержкой других сайтов.

**Comment by madonchik123** [comment]
> https://kinorium.com/
Да Возможно я сделал копию скрипта @Kirlovon с изменениями для kinorium можешь установить мою версию скрипта по следующей ссылке https://github.com/madonchik123/Kinorium-Watch/raw/main/Kinorium-Watch.user.js
